window._CCSettings = {
    platform: "web-mobile",
    groupList: ["default"],
    collisionMatrix: [
        [true]
    ],
    rawAssets: {
        assets: {
            "0": ["resources/font/font", 1, 1],
            "1": ["resources/font/font.fnt", 3],
            "2": ["resources/images/app/gameOver/share", 1, 1],
            "3": ["resources/image1/open_vedio_btn2x", 1, 1],
            "4": ["resources/images/back_slide2", 1, 1],
            "5": ["resources/images/app/gameOver/TryAgain", 1, 1],
            "6": ["resources/images/first_b2", 1, 1],
            "7": ["resources/images/app/gameOver/again", 1, 1],
            "8": ["resources/image1/share_groups_btn2x", 1, 1],
            "9": ["resources/image1/icon_cog", 1, 1],
            "10": ["resources/FloatingAd_resources/whiteBk", 1, 1],
            "11": ["resources/image1/free_get_btn2x", 1, 1],
            "12": ["resources/FloatingAd_resources/rqcodeicon.anim", 2],
            "13": ["resources/images/zen_title", 1, 1],
            "14": ["resources/image1/start_game_btn2x", 1, 1],
            "16": ["resources/leftView/cebian", 1, 1],
            "17": ["resources/images/tap_to_start", 1, 1],
            "18": ["resources/images/app/gameOver/rank", 1, 1],
            "19": ["resources/image1/icon_restart", 1, 1],
            "20": ["resources/image1/icon_volume_on", 1, 1],
            "21": ["resources/image1/icon_hint", 1, 1],
            "22": ["resources/leftView/cricleBtn", 1, 1],
            "23": ["resources/image1/pause", 1, 1],
            "24": ["resources/FloatingAd_resources/erweima.b741d", 1, 1],
            "25": ["resources/images/singleColor", 1, 1],
            "26": ["resources/image1/game_info_title2x", 1, 1],
            "27": ["resources/image1/add_my_applet", 1, 1],
            "28": ["resources/Collection_img/more_game_pop_up_bg", 1, 1],
            "29": ["resources/image1/perfect", 1, 1],
            "30": ["resources/image1/award_title2x", 1, 1],
            "31": ["resources/image1/hintmark", 1, 1],
            "32": ["resources/image1/on", 1, 1],
            "33": ["resources/images/game_btn_play1", 1, 1],
            "34": ["resources/leftView/texiaobg", 1, 1],
            "35": ["resources/images/back_side1", 1, 1],
            "36": ["resources/image1/everyday_award_title2x", 1, 1],
            "37": ["resources/image1/finger", 1, 1],
            "38": ["resources/Collection_img/player_number", 1, 1],
            "39": ["resources/images/app/gameOver/bg", 1, 1],
            "40": ["resources/image1/shine", 1, 1],
            "41": ["resources/images/black", 1, 1],
            "42": ["resources/Collection_img/pop_up_closed", 1, 1],
            "43": ["resources/image1/pop_up_close2x", 1, 1],
            "44": ["resources/image1/icon_hint_big", 1, 1],
            "54AZ9ZSo9GzownjUL0AX2m": ["resources/Collection_img/mask", 1, 1],
            f5e3FjCIpGv7mpzK0i2YpQ: ["resources/Collection_img/mask.png", 0],
            f11iiqnEhKNaWNBKe9Xb6e: ["resources/Collection_img/more_game_pop_up_bg.png", 0],
            deud4AlulH1pCbJSlOsvUs: ["resources/Collection_img/player_number.png", 0],
            f1zaFjyexBIZjaiWboBGVn: ["resources/Collection_img/pop_up_closed.png", 0],
            "3fVB+a3JdBSoO3Y6NblTCz": ["resources/FloatingAd_resources/circle_count_down", 1, 1],
            "2cHzowOKxFNqA+sZAsrbFf": ["resources/FloatingAd_resources/circle_count_down.png", 0],
            "20EK99pLtA97iY4YXEvG1Q": ["resources/FloatingAd_resources/erweima.b741d.png", 0],
            "09Mk/tvntDcpAkXcG/ZW5K": ["resources/FloatingAd_resources/landscape_try_btn", 1, 1],
            "39Z7Hw3eRLWK6g6QloBAUh": ["resources/FloatingAd_resources/landscape_try_btn.png", 0],
            ec3oSOraJKP6rzZFX93XOC: ["resources/FloatingAd_resources/pop_up_closed", 1, 1],
            "e68E7jJBdEIIztZQNbT/uu": ["resources/FloatingAd_resources/pop_up_closed.png", 0],
            b8U4R7DYNEh4vFXP6f6CyO: ["resources/FloatingAd_resources/title_mask", 1, 1],
            "f0ovrNbYZD/4glt6OFSFF0": ["resources/FloatingAd_resources/title_mask.png", 0],
            "53eMdsXA5N0riWfcgkcxvL": ["resources/FloatingAd_resources/whiteBk.png", 0],
            d8kz2kzvVL5JGPFVvmKuMJ: ["resources/font/font.png", 0],
            "dahuoyXZpMVoa6+/+bX5/T": ["resources/gamedata.json", 4],
            "8cTj+6gG5BmK44ObjnHh7q": ["resources/image1/Continue_btn", 1, 1],
            "c0RhPixqtAbJ3V4/ahMaw9": ["resources/image1/Continue_btn.png", 0],
            "371TeeQiBHr6ts/EXbZBdq": ["resources/image1/add_my_applet.png", 0],
            "d8SNBKUctH6r3ANF/c6FRc": ["resources/image1/award_title2x.png", 0],
            "1atKbONNBJjKkuCEOL8Lw9": ["resources/image1/bouns", 1, 1],
            "4cLcUFISJIJaiFBDxN+Mcw": ["resources/image1/bouns.png", 0],
            "56R7jEW7NPK53oFMk3LUU9": ["resources/image1/continue_play_game2x", 1, 1],
            ffFlCurk1IfLNL72jT1wbd: ["resources/image1/continue_play_game2x.png", 0],
            "97YSvv/hRJZKnTTBonBhf2": ["resources/image1/everyday_award_title2x.png", 0],
            f43mo7axNOmppd8J1vnFrv: ["resources/image1/finger.png", 0],
            "83K5bSO75Pn4eXJS30Y2cS": ["resources/image1/free_get_btn2x.png", 0],
            "89bVOOpAxMHZXY6qXQgxYz": ["resources/image1/game_info_title2x.png", 0],
            "2awBTX0gBM7b6sKtFWGPNn": ["resources/image1/hintmark.png", 0],
            "43Pse8x99DoKqy9O14P/p0": ["resources/image1/icon_cog.png", 0],
            "61MlBN0A1IPqtigYJX4pCS": ["resources/image1/icon_hint.png", 0],
            a9rMx0FXREALP8nvO7HBEh: ["resources/image1/icon_hint_big.png", 0],
            fce09a3a9IOpJMiG0o56Zj: ["resources/image1/icon_restart.png", 0],
            a5POqauihMU5wLqebytuiZ: ["resources/image1/icon_volume_off", 1, 1],
            e96eSqqS5EUouxm0GPf06f: ["resources/image1/icon_volume_off.png", 0],
            "62S3XeAnBLA50LlazKfrzQ": ["resources/image1/icon_volume_on.png", 0],
            "a3CKh66hdPV4zippmzA6D+": ["resources/image1/off", 1, 1],
            "49gUs4dlNDD4995b04Vbs/": ["resources/image1/off.png", 0],
            "08Pe0kK71CAJkE6Qr9cASq": ["resources/image1/on.png", 0],
            "c57su9UX1L/q6n7wKnCHxM": ["resources/image1/open_vedio_btn2x.png", 0],
            "0b6tsiv1tB/6a1vUyEdogn": ["resources/image1/pause.png", 0],
            c3qsIY99xJj4sinceiQMcl: ["resources/image1/perfect.png", 0],
            "ecjLUTG4JKfbM/wIBFav1p": ["resources/image1/pop_up_close2x.png", 0],
            "647vKKlAZBC7jYtzKWcQnQ": ["resources/image1/share_groups_btn2x.png", 0],
            "6a/1oEIxFKMamVgSY/9NL6": ["resources/image1/shine.png", 0],
            d8Wa1FNHxDO6P6cWJzX6Xm: ["resources/image1/start_game_btn2x.png", 0],
            "c03MFYqcpMIJ/lcdaf2R30": ["resources/image1/tap_to_start", 1, 1],
            "4eeMXkac5HV6VEumsmAY9P": ["resources/image1/tap_to_start.png", 0],
            "4aqlPED6dLFIaxQOpTrqK5": ["resources/image1/zen_title", 1, 1],
            "05iOKbPlxJhqm27aSJH+rG": ["resources/image1/zen_title.png", 0],
            "f0EDBk80tB37XEQeEr4/+9": ["resources/images/app/gameOver/TryAgain.png", 0],
            "89acBiyWFNHIBQOXEJqejM": ["resources/images/app/gameOver/again.png", 0],
            "81w9zqEDJGLJ/WGSSnAD6x": ["resources/images/app/gameOver/bg.png", 0],
            "60yuUFcH9N8btVxi8uMpQC": ["resources/images/app/gameOver/continue", 1, 1],
            "90Ni8++5NABLLmj3ioBcSb": ["resources/images/app/gameOver/continue.png", 0],
            "0ccNe/TPlN5658AnF6KRP8": ["resources/images/app/gameOver/rank.png", 0],
            "cdfK4YXAtHBrwAKHqCeU/N": ["resources/images/app/gameOver/share.png", 0],
            d686VVuB9O4KKWjWL1cMyl: ["resources/images/app/kuai", 1, 1],
            "002b1lrUBCCqmi8nok8as9": ["resources/images/app/kuai.png", 0],
            a1IGNOz4RIQK5e3T9TjOis: ["resources/images/app/trans-bg", 1, 1],
            "a9+KYLywxNdYivBlEZP410": ["resources/images/app/trans-bg.png", 0],
            "99pX7JqbdA9bohRbWd+Dtw": ["resources/images/back_side1.png", 0],
            "1brV/LjjRCUbrBQNwg0aKT": ["resources/images/back_slide2.png", 0],
            "491N6OFnRPL6DFmtIBNjBd": ["resources/images/black.png", 0],
            "0d6vplK9pIVIHMSk+acOBo": ["resources/images/finger", 1, 1],
            "50xvHYCyxIabSHveBvn8kA": ["resources/images/finger.png", 0],
            "84rtdkY/JL6a6baA1D+kJE": ["resources/images/first_b1", 1, 1],
            "0bPzfUTgxONJwC8Ue3LfTM": ["resources/images/first_b1.png", 0],
            "68uHhZXl1PebkkaHtliT9j": ["resources/images/first_b2.png", 0],
            "a1UV0QvtBJnLpNySFezS+L": ["resources/images/game_btn_play1.png", 0],
            "1e4bjXqTlBZKnfhpW7CpM7": ["resources/images/singleColor.png", 0],
            "79/nGJovtCzqkjYS8IgIPF": ["resources/images/tap_to_start.png", 0],
            "32pIBXNWVDDK3WkeZ+8SF1": ["resources/images/zen_title.png", 0],
            "8beBlPSM1IBIFpNIO+kXTO": ["resources/leftView/cebian.png", 0],
            e7vFxJQqFK75UxlsUD36Ye: ["resources/leftView/cricleBtn.png", 0],
            "3dzjERzMZJka9a5sApHP9k": ["resources/leftView/texiaobg.png", 0],
            "9a4UBTkTlGoIUP0UlnyGdo": ["resources/outlinedata.json", 4],
            d952xY8SZKVoqu1oHFY3Eh: ["resources/pieacedata.json", 4],
            "22CocxFwJGM5P0YgBHURqB": ["resources/reply.json", 4],
            e5iCX1R8tBQqXALUSlavYA: ["resources/sounds/bgm_game01.mp3", 5],
            "d9JYPalW5OMJKmK+N02vWl": ["resources/sounds/bgm_game02.mp3", 5],
            "9e8C8Ze9JKLo1aRogEVMBw": ["resources/sounds/se_block_release.mp3", 5],
            "f0wW6nX25HJ73CxDhuX+IZ": ["resources/sounds/se_block_return.mp3", 5],
            d8ktvHtc9Ny5t0du5wG32K: ["resources/sounds/se_block_select.mp3", 5],
            "27ap1zp3NIT5HkiKYa4KMu": ["resources/sounds/se_bonus_get.mp3", 5],
            "a77eWTiEVFfLK/0GwdVVnb": ["resources/sounds/se_hint.mp3", 5],
            "5ebs/G+6ZPF7lGMTuaqKjJ": ["resources/sounds/se_result_confeti.mp3", 5],
            "22DtVkuk5ATbcnkZcaKoB1": ["resources/sounds/sel_select.mp3", 5]
        },
        internal: {
            "71VhFCTINJM6/Ky3oX9nBT": ["image/default_btn_disabled.png", 0],
            "b4P/PCArtIdIH38t6mlw8Y": ["image/default_btn_pressed.png", 0],
            d8HsitJHxOYqo801xBk8ev: ["image/default_panel.png", 0],
            "6eBWFz0oVHPLIGQKf/9Thu": ["image/default_sprite.png", 0],
            "02delMVqdBD70a/HSD99FK": ["image/default_sprite_splash.png", 0]
        }
    },
    assetTypes: ["cc.Texture2D", "cc.SpriteFrame", "cc.AnimationClip", "cc.BitmapFont", "cc.RawAsset", "cc.AudioClip"],
    launchScene: "db://assets/scene/main.fire",
    scenes: [{
        url: "db://assets/scene/main.fire",
        uuid: 15
    }],
    packedAssets: {
        "066225939": [0, 1],
        "0f592d05e": [2, "01io0BljRIiZnR+G04h3hi", 3, 4, 5, 6, 7, 8, 9, "29FYIk+N1GYaeWH/q1NxQO", 10, 11, 12, 13, 14, 15, 16, 17, 18, "60IqepwjJO5pMYlMiFveYx", 19, 20, "64g0YAuqRMELshGzJEdJn/", 21, 22, "6buW04UDtDBI+u1uhxSI1/", 23, 24, "8c20Sso/ZEn7NUfNSM+EBh", "91tffpG0ZIcoN5o4R21+y0", "9bvaMerUlDyary99mJa6xp", "9b9Am0sO9MFqMFXbBYNGWU", 25, "a2MjXRFdtLlYQ5ouAFv/+R", 26, 27, 28, 29, 30, 31, 32, "caodawGmxEypfkV0mtxMcA", 33, 34, 35, 36, 37, 38, 39, "e97GVMl6JHh5Ml5qEDdSGa", "eaH+gpJCFFC7p4WLiiI3BJ", 40, "edFEHEBFpCQq/0Pmc2Ci98", 41, 42, 43, 44]
    },
    orientation: "portrait",
    uuids: ["d9rC27z+RLEJGZhoUWsPEE", "ebhkKAMslNOJZ1PjEMq3ji", "01SI7sQt1NOJHGbscpq674", "08d/mjOjVDmLiN0oaqCl+J", "0bRV4AWNhJd5M+SiGZ0J26", "10SYhz1qpB37gSDp3c6SM7", "1142+NRaFLQ7QufYOtorUd", "18wPYtHjNOpJdotCn4DP4Y", "1ayE1A/O1JDJVLEgmPTJYQ", "1bjHn5U8hP0aBgYwVqCYuA", "2bLjV8+iJNebDtTLeS654A", "3aKSjmW15Pe4yQdKEVtNqr", "42vFVzWrdOcbvxUM/h6FVd", "4egQSycfhIXLtVaQQ+AhQi", "53Jwoz2RFPWIbRQfHbLWPR", "54jHMCqlRFy5LfN7S4Lga8", "55ecWXQG1Ga7OufA5hL3Hf", "58x6h0AcdHZpTBYEi8PLJs", "5c/+MeKyJCU6jAUXGUEd8D", "62+OptkdJE7II5zDwSE4f2", "63iwGWKQZC0LHslL8USCgj", "67HVqFvKhGs6OYavMjD7zW", "68oUT0uZFDUI4+a1/0ndQ5", "77W18WBiVFho/o5Y2SCQrB", "7bWQ1JP2dMhK58eKt3rpVB", "9cp/53k2NAnYxUQBT++9qc", "b0S+RY5C9J/pQtVNFKiqlM", "b3sO4y+RhOnrQH4D9kTXoz", "b5tJ9tlfFEtIAs0loMWEOR", "bffAJK4JlOV73FBcomtkgY", "c1igxyvnRBa4xrDV7d8rXz", "c4ewpD2n1DGr4ucgOV2LF0", "c7I7To6wpA8KQnTno/S3Ul", "cbZWgD3OlCXaK6quJanqmT", "cbo4y41vBHbIikBwFqtdsB", "d0CSCF/mtIq7KrwTAgVn6l", "d0wWVC0wVA16oVpL0cSADA", "dbFr7gkepJd5gnz8BJmSJ2", "db8IUgUiRKkZIz94oH2061", "e8M+e56AdNOrIGKuFxG0Jt", "ecAPD2ZsFMHpoWVnkGPAAO", "f0De+xm5xDnJW325HmPvKU", "f25jS4sedDuYfTCPgZwAbr", "fbv22rKhJDLIt6CaEToRc/", "ffF590Yf5G8pL8vSM1L++J"]
};